### ISSUE TITLE
Model Capabilities in the Analyses

### ISSUE THREAD

**Issue by samarth-aws** [awslabs/ar-go-tools#45]
Google's new `capslock` tool contains the ability to reason about the ["capabilities"](https://github.com/google/capslock/blob/main/docs/capabilities.md) of various functions and packages in the Go standard library. It would be nice if we could have the dataflow analyses reason about these same capabilities to be able to prove more powerful propositions.

For example, a possible proposition that can be proven via the taint analysis is: "no data that is read from a network can be used to modify the system state or file system". Without the capabilities feature, you would have to manually list every possible function/method/interface that can perform a network read or modify the system state.

Example config file:
```yaml
taint-tracking-problems:
  -
    sources:
      - capability: "NETWORK"
    sinks:
      - capability: "FILES"
      - capability: "MODIFY_SYSTEM_STATE"
```
